### ISSUE TITLE
RInside cannot find Rcpp in non-default library locations at runtime

### ISSUE THREAD

**Issue by bjmt** [eddelbuettel/rinside#41]
I have all of my R packages (including Rcpp) stored in a folder in my home directory (on macOS). This isn't a problem when it comes to compiling something using RInside (using your example Makefiles as a model). However when I first tried to run my program I got the following error:

```
Error: function 'dataptr' not provided by package 'Rcpp'
In addition: Warning message:
In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘Rcpp’
Execution halted
```

I got around it pretty easily by setting the `R_LIBS` environment variable, such as when running the program (`$ R_LIBS=/path/to/library ./program`).

At first I thought the issue was due to me using the prebuilt binaries from CRAN (since to me it looks as if `R_LIBS` is hard coded into the library at compile time), so I installed the source package -- no luck. I'm not quite sure why, since when I run `R -q -e "Sys.getenv()"` (where RInside seems to be getting its information from based on `RInsideEnvVars.r`) my `R_LIBS` variable is properly showing where my library is (set in `~/.Renviron`). Maybe I'm misunderstanding something however.

In any case, I just thought this was a bit of a strange error initially and not something I could find anyone else running into. Perhaps you won't consider it an error with RInside itself however -- I apologize if that's the case.

**Comment by eddelbuettel** [comment]
I think this is standard and expected behaviour: _if_ you have R libraries in non-standard location, you _must_ declare those to R.  Using `R_LIBS` is one of several settings.  See `help(Startup)` for more.

I do not think we have a bug here so I am going to close this.  If you think there is something at fault with RInside, and you can create a reproducible example, please feel free to reopen it.
